name: Continuos Integration

on:
  pull_request:
    branches:
      ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run:  docker build -t lauroappelt/eventosfull:${{ github.event.pull_request.head.sha }} .

      - name: Start container
        run:  docker run -d --name hyperf lauroappelt/eventosfull:${{ github.event.pull_request.head.sha }}

      - name: unit-tests
        run: docker exec hyperf composer test
        
      - name: cd-check
        run: docker exec hyperf composer cs-check

      - name: Run sast
        run: docker exec hyperf composer analyse

  #     - name: Publish image to docker hub
  #       run: docker push lauroappelt/eventosfull:${{ github.event.pull_request.head.sha }}

  # unit-tests:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Login to docker hub
  #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Start container
  #       run:  docker run -d --name hyperf lauroappelt/eventosfull:${{ github.event.pull_request.head.sha }}

  #     - name: Run tests
  #       run: docker exec hyperf composer test

  # cs-check:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Login to docker hub
  #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Start container
  #       run:  docker run -d --name hyperf lauroappelt/eventosfull:${{ github.event.pull_request.head.sha }}

  #     - name: Run cs
  #       run: docker exec hyperf composer cs-check

  # SAST:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Login to docker hub
  #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Start container
  #       run:  docker run -d --name hyperf lauroappelt/eventosfull:${{ github.event.pull_request.head.sha }}

  #     - name: Run sast
  #       run: docker exec hyperf composer analyse