name: Continuos Integration

on:
  pull_request:
    braches:
      ['master']

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run:  docker build -t hyperf .

      - name: Start container and run tests
        run:  docker run -d --name hyperf hyperf

      - name: Run tests
        run: docker exec hyperf composer test
