name: Continuos Integration

on:
  pull_request:
    branches:
      ['main']

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run:  docker build -t hyperf .

      - name: Start container
        run:  docker run -d --name hyperf hyperf

      - name: Run tests
        run: docker exec hyperf composer test

      - name: Teste
        run: echo $env.APP_NAME
