name: Deploy Application

on:
  release:
    types: ['published']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.release.tag_name }}'
      
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build docker image
        run: docker build -t lauroappelt/eventosfull:${{ github.event.release.tag_name }} .
      
      - name: Start container
        run:  docker run -d --name eventosfull lauroappelt/eventosfull:${{ github.event.release.tag_name }}

      - name: Run tests
        run: docker exec eventosfull composer test
      
      - name: Publish image to docker hub
        run: docker push lauroappelt/eventosfull:${{ github.event.release.tag_name }}

  deploy:
    needs: build
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Pull image from docker hub
        run: docker pull lauroappelt/eventosfull:${{ github.event.release.tag_name }}
      
      - name: Stop container
        run: docker stop eventosfull-prod

      - name: Delete old container
        run: docker rm -f eventosfull-prod 

      - name: Run docker container
        run: docker run -d --name eventosfull-prod 
          --network eventosfull-net 
          -p 9501:9501 
          -e DB_DRIVER=${{vars.DB_DRIVER}} 
          -e DB_HOST=${{vars.DB_HOST}} 
          -e DB_PORT=${{vars.DB_PORT}} 
          -e DB_DATABASE=${{vars.DB_DATABASE}} 
          -e DB_USERNAME=${{vars.DB_USERNAME}} 
          -e DB_PASSWORD=${{vars.DB_PASSWORD}} 
          lauroappelt/eventosfull:${{ github.event.release.tag_name }}

      - name: Run migration
        run: docker exec eventosfull-prod php bin/hyperf.php migrate
